### ISSUE TITLE
Prompts.js function not working.

### ISSUE THREAD

**Issue by rolandobrown** [stefania11/littlebig#56]
Hey @drewprice,

Can't get this prompts.js replace accordion toggle text working.

See branch: 
https://github.com/stefania11/littlebig/tree/default_show_image

Thought you might be able to spot it quickly and tell me what I'm doing wrong, or not doing.

Thanks!

**Comment by notnotdrew** [comment]
@rolandobrown I'm having trouble spotting the problem—where exactly do you run into the issue?

**Comment by rolandobrown** [comment]
When you go to a prompt that has an image and click on close image. It should change the text to open image. 

Best,

Grow

---

Growth Strategist & Engineer for: www.advocacy-institute.org

Advisor to: www.techsuperwomensummit.com

Board Member: www.mocada.org

Consulting: www.madetogrow.us

Coaching: www.trainyouremail.com

"I want to grow. I want to be better. You Grow. We all grow. We're made to grow. 

You either evolve or you disappear." 
—Tupac Amaru Shakur

**Comment by notnotdrew** [comment]
Duck-taped: use 'Toggle image' rather than toggling between 'show' and 'hide',
